version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo Build completed
      - mv target/*.jar musala.jar
artifacts:
  files:
    - appspec.yml
    - target/musala.jar
  discard-paths: yes