version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - **/*
  discard-paths: yes